<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE thresholds [
<!ELEMENT thresholds (threshold)+>
<!ELEMENT threshold (description , levels)>
<!ELEMENT description (CDATA)>
<!ELEMENT levels (CDATA)>
<!ATTLIST threshold map ID #REQUIRED>
<!ATTLIST levels width CDATA #REQUIRED>
<!ATTLIST levels height CDATA #REQUIRED>
<!ATTLIST levels divisor CDATA #REQUIRED>
]>
<thresholds>
  <threshold map="h85lines">
    <description>Halftone 85 lines/inch (angled)</description>
    <levels width="20" height="20" divisor="219">
      218 215 171  65  29   7  12  54 154 196 217 213 170  64  28   5  11  53 152 195
      199 184 144  96  50  23  40  77 126 176 197 183 143  95  49  22  38  77 125 175
      160 135 119 109  93  61  86 102 112 126 159 134 118 108  92  60  84 102 111 127
       55  72  97 116 140 167 148 122 103  79  55  71  96 114 139 166 147 121 104  79
       15  32  68 130 179 208 190 154  86  41  13  30  66 130 178 206 189 155  87  42
        4   9  52 151 193 217 209 168  61  25   2   8  51 150 191 216 211 169  63  26
       20  36  76 123 173 200 180 142  93  46  19  35  75 123 172 201 181 142  94  47
       59  83 101 110 128 160 135 116 106  89  58  82  99 110 129 162 136 117 107  90
      164 146 120 105  80  56  72  98 113 137 163 145 120 105  82  57  73  99 114 138
      204 187 155  87  43  16  32  68 132 176 202 186 157  89  44  17  34  69 132 177
      217 212 170  64  27   5  10  53 151 194 217 214 170  65  28   6  11  53 153 196
      197 182 143  95  48  21  37  76 124 174 198 183 143  95  49  23  39  77 125 175
      158 133 117 107  91  60  84 101 111 127 159 134 119 108  92  60  85 102 112 126
       54  70  96 114 139 165 147 120 104  79  55  71  97 115 139 166 147 122 102  78
       13  30  66 129 178 205 188 154  86  41  14  31  67 130 179 207 189 153  86  40
        1   8  50 149 191 216 210 168  62  25   3   9  51 150 192 216 208 167  61  24
       18  35  74 122 171 201 181 142  93  46  20  36  75 123 172 200 180 141  93  45
       57  82  99 109 128 161 136 116 107  90  59  82 100 110 128 160 135 116 106  89
      162 145 119 105  81  57  73  98 113 138 163 146 120 104  80  56  72  97 113 136
      202 185 156  88  44  16  33  69 132 177 203 186 155  87  42  15  32  68 131 176
    </levels>
  </threshold>

  <threshold map="h70lines">
    <description>Halftone 70 lines/inch (angled)</description>
    <levels width="24" height="24" divisor="389">
      375 359 324 160 108  43  15  33  77 238 290 352 377 361 322 159 106  41  14  32  76 237 288 350
      329 310 269 181 131  94  60  82 121 219 260 299 330 311 270 179 131  93  60  81 122 217 259 297
      139 150 172 199 214 233 255 244 224 194 184 163 141 152 174 200 213 231 253 242 223 192 183 162
       61  96 123 203 255 282 329 295 265 190 135 111  63  96 124 205 257 281 327 293 264 188 133 109
       17  35  83 225 274 342 373 355 307 169 115  47  18  35  85 225 275 344 372 356 305 167 114  45
        1   7  50 246 315 366 388 381 337 146  68  24   2   8  52 247 317 367 388 379 335 144  67  21
       11  29  73 235 284 353 377 363 321 157 104  39  13  31  74 236 286 354 378 365 320 157 102  38
       57  78 119 216 262 301 332 312 272 179 130  92  58  79 120 215 263 303 333 313 273 177 129  90
      250 240 220 195 186 164 142 153 175 201 211 230 251 241 221 197 187 166 144 155 176 203 210 229
      324 291 267 191 136 111  64  98 126 206 258 280 326 291 269 191 138 113  65 100 128 208 259 280
      370 357 307 169 117  46  19  36  86 226 277 346 371 358 309 170 119  49  22  37  88 227 279 348
      387 383 339 147  69  25   3   9  53 247 317 368 386 385 341 149  71  27   5  10  55 249 318 369
      377 360 322 158 105  40  14  32  75 236 287 349 374 359 323 160 107  42  15  33  77 238 289 351
      330 311 270 179 131  93  59  80 121 217 259 296 328 310 269 180 131  94  60  82 121 218 260 298
      140 151 173 200 212 231 252 242 222 192 182 161 139 150 171 198 214 232 254 243 224 193 184 163
       62  95 124 204 256 281 327 292 264 188 132 109  61  95 123 203 254 282 328 294 265 189 134 111
       18  34  84 225 275 343 372 355 304 167 114  44  16  34  82 225 274 341 373 355 307 169 115  46
        2   8  51 247 317 366 387 379 334 143  66  20   1   6  50 245 314 366 387 380 336 145  68  23
       12  30  74 236 285 354 378 364 319 156 101  38  10  28  72 234 283 353 376 362 321 156 103  39
       58  79 120 215 263 302 333 313 273 177 129  89  56  78 119 215 261 300 331 312 271 178 130  91
      251 241 221 196 187 165 144 154 176 202 209 228 250 239 220 195 185 164 142 153 174 201 211 230
      325 291 268 191 137 112  65  99 127 207 259 280 324 291 266 191 136 110  64  97 125 206 258 280
      371 358 308 170 118  48  21  37  87 227 278 347 370 357 306 168 116  46  19  36  86 226 276 345
      386 384 340 148  70  26   4  10  54 248 318 369 387 382 338 146  69  25   3   9  53 247 316 368
    </levels>
  </threshold>

  <threshold map="h60lines">
    <description>Halftone 60 lines/inch (angled)</description>
    <levels width="56" height="28" divisor="409">
      278 262 234 219 209 193 166 143 160 186 203 211 226 254 278 260 234 217 208 191 165 143 158 184 201 211 227 255 278 262 234 219 209 193 166 143 160 186 203 211 226 254 278 260 234 217 208 191 165 143 158 184 201 211 227 255
      355 328 307 243 195 131 101  61  93 116 178 226 291 318 354 326 305 242 195 131 101  61  90 114 178 224 290 318 354 328 307 243 195 131 101  61  93 116 178 226 291 318 354 326 305 242 195 131 101  61  91 114 178 224 290 318
      393 383 340 272 169 107  48  23  35  83 147 254 316 371 392 382 339 271 169 106  46  21  36  81 145 252 316 372 393 383 340 272 169 107  48  23  35  83 147 254 316 371 392 382 339 271 169 105  46  21  36  81 146 252 316 372
      406 405 368 299 149  67  25   7  10  52 124 276 348 391 407 404 366 297 149  65  25   4  11  52 124 276 348 390 406 405 368 299 149  67  25   7  10  52 124 276 348 391 407 404 366 297 149  65  25   4  11  52 124 276 348 390
      397 384 354 287 161  98  42  17  32  72 136 260 324 376 400 386 352 286 161  96  40  15  29  70 135 259 324 374 397 384 353 287 161  98  42  17  32  72 136 260 324 376 400 386 351 286 161  96  40  15  29  70 135 259 324 374
      359 341 308 250 188 121  86  57  76 110 172 232 300 332 360 341 309 249 187 119  87  56  76 110 171 231 298 331 359 341 308 250 188 121  86  57  76 111 172 232 300 332 360 341 309 249 187 119  86  56  76 110 171 231 298 332
      292 280 244 218 205 182 155 128 140 175 200 213 238 266 293 282 245 220 205 181 153 127 139 174 198 212 237 264 292 280 244 219 205 182 155 128 140 175 200 213 238 266 293 282 245 220 205 181 153 127 139 174 198 212 237 264
      139 156 183 200 208 228 256 281 262 236 216 206 189 164 141 156 183 200 209 228 256 279 263 235 215 206 189 162 139 156 183 200 208 228 256 281 262 236 216 206 189 164 141 156 183 200 209 228 256 279 263 235 215 206 189 162
       59  89 112 175 223 289 321 359 330 305 241 193 130 100  59  91 115 177 223 289 319 357 328 303 241 192 130  98  59  89 112 175 223 289 321 359 330 305 241 193 130 100  59  91 114 177 223 289 319 357 328 303 241 192 130  98
       19  31  78 144 251 313 367 395 380 338 269 167 105  44  18  34  80 145 251 315 370 395 380 336 269 167 103  43  19  31  78 144 251 313 367 395 380 338 269 167 105  44  18  34  80 145 251 315 370 396 380 336 269 167 103  43
        1   5  47 121 273 344 389 408 402 364 295 148  65  24   2   9  50 122 274 346 389 407 403 364 295 148  63  22   1   5  47 120 273 344 389 408 402 364 295 148  65  24   2   8  50 122 274 346 389 407 403 364 295 148  63  22
       12  26  68 133 257 320 375 399 387 350 285 160  94  39  13  28  68 134 257 322 378 401 388 349 284 159  94  37  12  26  68 132 257 320 375 399 387 350 285 160  94  39  13  28  68 134 257 322 378 401 388 349 284 159  94  37
       54  72 109 169 230 302 334 362 343 311 249 187 118  85  56  74 109 171 231 301 336 362 345 312 248 185 118  84  54  72 109 169 230 302 334 362 343 311 249 187 118  85  56  74 109 171 231 301 336 362 345 312 248 185 118  84
      125 137 173 196 213 239 265 294 283 246 220 203 181 153 127 137 173 198 214 239 267 294 283 246 221 202 179 151 125 137 173 196 213 239 265 294 283 246 220 203 181 153 127 137 173 198 214 239 267 294 283 246 221 202 179 151
      277 259 234 217 207 190 164 142 157 184 201 210 227 254 277 261 233 218 208 192 165 142 159 185 202 210 226 253 277 259 234 217 207 191 164 142 157 184 201 210 227 255 278 261 233 218 209 192 165 142 159 185 202 210 225 253
      354 325 304 242 194 130 101  61  90 113 178 224 290 317 354 327 306 243 194 131 101  60  92 115 177 225 291 317 354 325 304 242 194 130 101  61  90 113 178 224 290 317 354 327 306 243 194 131 101  60  92 116 177 225 291 317
      392 381 339 270 168 105  45  21  35  80 145 252 316 371 393 383 339 272 168 107  47  22  35  82 147 253 316 371 392 381 339 270 168 105  45  20  35  80 145 252 316 371 393 383 339 272 168 107  47  22  35  82 147 253 316 371
      407 404 365 296 149  64  25   4  11  52 123 275 348 390 406 405 367 298 149  66  25   6  10  51 123 275 347 391 407 404 365 296 149  64  25   3  11  52 123 275 348 390 406 405 367 298 149  66  25   7  10  52 123 275 347 391
      399 385 351 285 161  95  40  14  28  69 134 258 323 373 397 383 353 287 161  97  41  16  31  72 136 259 324 376 399 385 351 285 161  95  39  14  28  69 134 258 323 373 397 383 353 287 161  97  41  16  31  72 136 259 324 376
      360 341 308 249 186 119  86  55  75 110 170 230 297 331 358 341 308 250 187 121  86  57  75 110 171 232 299 331 360 340 308 249 186 119  86  55  75 110 170 230 297 331 359 341 308 250 187 121  86  57  75 110 171 232 299 331
      293 281 244 219 205 181 153 127 138 174 198 211 236 264 292 280 243 218 204 182 154 128 140 175 199 213 238 265 293 281 245 219 205 181 153 127 138 174 198 211 236 264 292 280 243 218 204 182 154 128 140 175 199 213 237 265
      140 156 183 200 209 228 255 278 262 234 215 205 189 162 138 155 183 200 207 228 256 280 262 236 215 206 189 163 140 156 183 200 209 228 255 278 262 235 215 205 189 162 138 155 183 200 207 228 256 280 262 236 215 205 189 163
       58  90 114 176 222 288 319 357 327 303 240 192 129  97  59  88 112 175 223 289 320 359 330 305 240 193 129  99  58  90 114 176 222 288 319 356 327 303 240 192 129  97  59  88 112 175 223 289 320 359 329 305 240 193 129  99
       18  33  80 145 250 314 369 395 379 335 268 166 102  43  18  30  77 144 251 312 367 394 379 337 268 166 104  43  18  33  79 145 250 314 370 395 379 335 268 166 102  43  18  30  77 144 251 312 367 394 379 337 268 166 104  43
        2   8  49 122 274 346 389 407 403 364 295 147  62  22   1   5  47 120 272 343 389 408 402 363 295 147  64  24   1   8  49 122 274 346 389 407 402 363 295 147  62  22   1   5  47 120 272 343 389 407 402 363 295 147  65  24
       13  28  67 133 257 322 377 401 387 349 284 158  94  37  12  26  68 132 257 320 375 398 387 350 285 160  94  38  13  27  67 134 257 322 377 401 388 349 284 158  94  37  12  26  68 132 257 320 375 398 387 350 285 160  94  38
       55  73 108 170 230 301 336 362 344 312 247 185 117  84  53  71 108 168 229 301 333 361 342 310 249 186 117  84  56  73 108 170 230 301 336 362 344 312 247 185 117  84  53  71 108 168 229 301 333 361 342 310 248 186 117  84
      126 137 173 197 213 238 266 294 282 245 220 201 178 150 125 137 172 196 212 238 265 293 282 245 220 202 180 152 126 137 173 197 213 238 266 294 282 245 220 201 178 150 125 137 172 196 212 238 265 293 282 245 220 202 180 152
    </levels>
  </threshold>
</thresholds>
